### PR TITLE
2 clean-up fixes

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @jamesderlin

**Comment by jamesderlin** [comment]
LGTM (for whatever that's worth; I don't have commit access to this repository).

**Comment by kevmoo** [comment]
> LGTM (for whatever that's worth; I don't have commit access to this repository).

Ha! who does?

**Comment by kevmoo** [comment]
Looks like @johnsonmh has keys!

**Pull request merged**
