### PR TITLE
Update the github actions CI

### PR DESCRIPTION
**Pull request by devoncarew**
Update the github actions CI:
- run `dart analyze` as part of the CI
- use `dart pub get` instead of `pub get`

### CODE REVIEW

**Comment by devoncarew** [comment]
It looks like there are a few issues:

```
warning - analysis_options.yaml:1:10 - The include file 'package:pedantic/analysis_options.1.8.0.yaml' in '/__w/dart-basics/dart-basics/analysis_options.yaml' can't be found when analyzing '/__w/dart-basics/dart-basics'. - include_file_not_found
warning - pubspec.yaml:9:1 - The 'authors' field is no longer used and can be removed. Try removing the field. - deprecated_field
```

**Comment by jamesderlin** [comment]
I have an existing PR (https://github.com/google/dart-basics/pull/38) that also removes the `authors` field from `pubspec.yaml`.

**Comment by devoncarew** [comment]
Gotcha. Not sure who reviews this repo, but if your PR lands first, I can rebase this.

**Comment by jamesderlin** [comment]
@johnsonmh owns this repo and usually reviews PRs. (By coincidental timing, different people have submitted PRs over the past few days, and now there's a backlog.)

**Comment by devoncarew** [comment]
@johnsonmh - do you mind reviewing this?

**Comment by jamesderlin** [comment]
@devoncarew Maybe ping @johnsonmh through internal channels?  There's a backlog of PRs, and I think he's probably the only person with merge access.

**Comment by johnsonmh** [comment]
Sorry I missed these messages, thanks for the ping @devoncarew !

LGTM

**Pull request merged**
